services:
  app:
    build:
      context: ./docker/php
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -lc "
        mkdir -p storage bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        chmod -R ug+rwx storage bootstrap/cache &&
        php-fpm
      "


  web:
    image: nginx:1.25
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -ppassword -h 127.0.0.1 --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "18025:8025"
    restart: unless-stopped

volumes:
  db-data:
